---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-vvv'

images:
  base_image:
    name: registry.access.redhat.com/ubi9/ubi-micro:latest

additional_build_files:
  - src: ansible.cfg
    dest: configs/
  - src: requirements.txt
    dest: configs/
  - src: requirements.yml
    dest: configs/
  - src: ansible/
    dest: ansible/

# NOTE: ansible-builder will ignore most of this when using custom Containerfile
# The actual build logic is in Containerfile.ubi-micro
dependencies:
  python: requirements.txt
  galaxy: requirements.yml