---
version: 3

images:
  base_image:
    name: quay.io/ansible/creator-base:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_base:
    - RUN whoami
    - RUN cat /etc/os-release
  prepend_galaxy:
    - COPY ansible.cfg /etc/ansible/
  prepend_final:
    - RUN ls -la /usr/share/ansible/collections/
    - RUN ansible-galaxy collection list
