---
version: 3

images:
  base_image:
    name: registry.redhat.io/ubi9/python-311:latest

additional_build_files:
  - src: ansible.cfg
    dest: configs/

dependencies:
  # Install ansible-core first, before galaxy collections
  ansible_core:
    package_pip: ansible-core>=2.17.0
  # Install ansible-runner (required for execution environments)
  ansible_runner:
    package_pip: ansible-runner>=2.3.0
  # Python dependencies
  python: requirements.txt
  # System packages
  system: bindep.txt
  # Galaxy collections (installed after ansible-core)
  galaxy: requirements.yml

additional_build_steps:
  prepend_base:
    # Install Python 3.11 and essential packages
    - RUN dnf update -y && dnf install -y python3.11 python3.11-pip git openssh-clients && dnf clean all
    # Set Python 3.11 as the default python3
    - RUN alternatives --set python3 /usr/bin/python3.11 || update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
  prepend_galaxy:
    # Verify ansible-core and ansible-runner installation before galaxy operations
    - RUN ansible --version
    - RUN ansible-galaxy --version
    - RUN ansible-runner --version
  append_final:
    # Copy ansible configuration
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    # Verify ansible configuration
    - RUN cat /etc/ansible/ansible.cfg
