name: 'Setup Ansible Environment'
description: 'Sets up Python and Ansible with common dependencies'

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.11'
  install-lint-tools:
    description: 'Whether to install linting tools (ansible-lint, yamllint)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Ansible and dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install ansible-core>=2.14

    - name: Install linting tools
      if: inputs.install-lint-tools == 'true'
      shell: bash
      run: |
        pip install ansible-lint
        pip install yamllint

    - name: Install collection dependencies
      if: inputs.install-lint-tools == 'true'
      shell: bash
      run: |
        ansible-galaxy collection install -r ansible/requirements.yml --force
