---
- name: Ensure output directory exists on control node
  ansible.builtin.file:
    path: "{{ core_dump_ed_25_03_output_dir }}"
    state: directory
    mode: "0755"
  delegate_to: localhost

- name: Assert explicit confirmation variables are set
  ansible.builtin.assert:
    that:
      - core_dump_ed_25_03_perform_core_dump | bool
      - core_dump_ed_25_03_confirm_manual_power_cycle | bool
      - core_dump_ed_25_03_core_dump_ack_text | length > 20
    fail_msg: >-
      Core dump is DANGEROUS and triggers immediate reload. Set:
      core_dump_ed_25_03_perform_core_dump=true,
      core_dump_ed_25_03_confirm_manual_power_cycle=true,
      core_dump_ed_25_03_core_dump_ack_text='<type a long explicit acknowledgment>'

- name: Save operator acknowledgment
  ansible.builtin.copy:
    dest: "{{ core_dump_ed_25_03_output_dir }}/core_dump_ack.txt"
    content: |-
      {{ core_dump_ed_25_03_core_dump_ack_text }}
    mode: "0600"
  delegate_to: localhost

- name: Disable terminal pager
  cisco.asa.asa_command:
    commands:
      - terminal pager 0

- name: Pre-step reboot note (per CISA guidance)
  ansible.builtin.debug:
    msg: >-
      Ensure the device has been power cycled prior to core dump to
      maximize success, as per CISA ED 25-03. This role does NOT power cycle.

- name: Configure ASA to enable core dump to filesystem
  cisco.asa.asa_config:
    lines:
      - coredump enable filesystem {{ core_dump_ed_25_03_filesystem }}
    save_when: never

- name: Initiate core dump (this triggers IMMEDIATE reload)
  cisco.asa.asa_command:
    commands:
      - crashinfo force page-fault
  register: crash_cmd
  ignore_errors: true

- name: Save crash command output
  ansible.builtin.copy:
    dest: "{{ core_dump_ed_25_03_output_dir }}/core_dump_trigger_output.txt"
    content: "{{ crash_cmd.stdout | default([]) | join('\n') }}\n"
    mode: "0644"
  delegate_to: localhost

- name: Wait for expected reload interval (best effort)
  when: core_dump_ed_25_03_attempt_reconnect | bool
  ansible.builtin.wait_for:
    timeout: "{{ core_dump_ed_25_03_expected_reload_seconds }}"
  delegate_to: localhost
