---
galaxy_info:
  author: Kush Gupta
  description: Check for firmware update logs and patching evidence
  license: Apache-2.0
  min_ansible_version: 2.17.0
dependencies: []
collections:
  - cisco.asa
  - ansible.netcommon
