name: 'Validate Ansible Collection'
description: 'Runs linting and validation on Ansible collection'

inputs:
  collection-path:
    description: 'Path to the collection directory'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run ansible-lint on collection
      shell: bash
      run: |
        ansible-lint ${{ inputs.collection-path }}

    - name: Run ansible-lint on playbooks
      shell: bash
      run: |
        cd ansible
        ansible-lint --config-file .ansible-lint playbooks/

    - name: Run yamllint on collection
      shell: bash
      run: |
        yamllint ${{ inputs.collection-path }}

    - name: Validate galaxy.yml
      shell: bash
      run: |
        python -c "
        import yaml
        import sys
        try:
            with open('${{ inputs.collection-path }}/galaxy.yml', 'r') as f:
                data = yaml.safe_load(f)
            required_fields = ['namespace', 'name', 'version', 'description', 'authors']
            for field in required_fields:
                if field not in data or not data[field]:
                    print(f'Missing or empty required field: {field}')
                    sys.exit(1)
            print('galaxy.yml validation passed')
        except Exception as e:
            print(f'galaxy.yml validation failed: {e}')
            sys.exit(1)
        "
